services:
  - type: web
    name: vnfood-backend
    env: python
    root: backend
    buildCommand: pip install -r requirements.txt && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
